lineabase/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import *

urlpatterns =  [
    url(r'^inicio/', homePageViewLineaBase, name='index-linea-base'),
    url(r'^consultar/', consulta_herramienta, name='linea-consulta'),
    url(r'^consultar-establecimiento/', consulta_establecimiento, name='consulta-establecimiento'),
    url(r'^fichas/', TemplateView.as_view(template_name="fichas_cuadernos.html")),
    url(r'^acerca-practicas/', TemplateView.as_view(template_name="acerca_practicas.html")),
    url(r'^mapa-datos/', TemplateView.as_view(template_name="mapa_datos.html")),
    url(r'^entrevistados-autocomplete/',
        EntrevistadosAutocomplete.as_view(),
        name='entrevistados-autocomplete',),
    url(
        r'^departamento-autocomplete/',
        DepartamentoAutocomplete.as_view(create_field='nombre'),
        name='depart-autocomplete',
    ),
    url(
        r'^municipio-autocomplete/',
        MunicipioAutocomplete.as_view(create_field='nombre'),
        name='municipio-autocomplete',
    ),
    url(
        r'^comunidad-autocomplete/',
        ComunidadAutocomplete.as_view(create_field='nombre'),
        name='comunidad-autocomplete',
    ),
    url(r'^api/productor/', get_productor, name='productor-search'),
    url(r'^ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
    url(r'^ajax/load-municipios/', load_municipios, name='ajax_load_municipios'),
    url(r'^ajax/load-comunidad/', load_comunidades, name='ajax_load_comunidad'),
    url(r'^mapaherramienta/', obtener_lista_mapa_cacao, name='obtener-lista-mapa-cacao'),
    url(r'^(?P<vista>\w+)/$', get_view, name='get-view'),
]

rentabilidad/urls.py
from django.conf.urls import url
from .views import *
from django.views.generic import TemplateView

urlpatterns =  [
    url(r'^consultar-rentabilidad/', consulta_ficha, name='consulta-rentabilidad'),
    #url(r'^api/productor/', get_productor, name='productor-search'),
    #url(r'^ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
    #url(r'^ajax/load-municipios/', load_municipios, name='ajax_load_municipios'),
    #url(r'^ajax/load-comunidad/', load_comunidades, name='ajax_load_comunidad'),
    #url(r'^mapaherramienta/', obtener_lista_mapa_cacao, name='obtener-lista-mapa-cacao'),
    url(r'^(?P<vista>\w+)/$', get_view, name='get-view'),
]

sistemahelvetica/urls.py
# -*- coding: utf-8 -*-
"""sistemahelvetica URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from cuadernosmes0.views import IndexView

admin.site.site_title = "Sitio Administrativo de CCI"
admin.site.site_header = "CCI Administración"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^linea-base/', include('lineabase.urls')),
    url(r'^cuaderno-mes-seis/', include('cuadernosmes6.urls')),
    url(r'^cuaderno-mes-nueve/', include('cuadernosmes9.urls')),
    url(r'^cuaderno-mes-tres/', include('cuadernosmes3.urls')),
    url(r'^cuaderno-mes-cero/', include('cuadernosmes0.urls')),
    url(r'^transformacion/', include('transformacion.urls')),
    url(r'^rentabilidad/', include('rentabilidad.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += staticfiles_urlpatterns()

lugar/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible


from django.db import models
from django.template import defaultfilters

# Create your models here.

@python_2_unicode_compatible
class Pais(models.Model):
    nombre = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, editable=False)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Países"
        unique_together = ('nombre',)

    def save(self, *args, **kwargs):
      self.slug = defaultfilters.slugify(self.nombre)
      super(Pais, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

@python_2_unicode_compatible
class Departamento(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    class Meta:
        verbose_name = 'Departamento/Provincia'
        verbose_name_plural = "Departamentos/Provincias"
        unique_together = ('nombre',)
        ordering = ['nombre']

    def save(self, *args, **kwargs):
      self.slug = defaultfilters.slugify(self.nombre)
      super(Departamento, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

@python_2_unicode_compatible
class Municipio(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=130, unique=True)
    slug = models.SlugField(max_length=130, unique=True, editable=False)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Municipios"
        unique_together = ('nombre','departamento',)
        ordering = ['departamento__nombre', 'nombre']

    def save(self, *args, **kwargs):
      self.slug = defaultfilters.slugify(self.nombre)
      super(Municipio, self).save(*args, **kwargs)

    def __str__(self):
        return '%s - %s' % (self.departamento.nombre, self.nombre)

@python_2_unicode_compatible
class Comunidad(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=140)
    slug = models.SlugField(max_length=140, editable=False)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    class Meta:
        verbose_name_plural="Comunidades"
        unique_together = ('nombre','municipio',)
        ordering = ['nombre']

    def save(self, *args, **kwargs):
      self.slug = defaultfilters.slugify(self.nombre)
      super(Comunidad, self).save(*args, **kwargs)

    def __str__(self):
        return u'%s' % self.nombre

rentabilidad/forms.py
# -*- coding: utf-8 -*-
from django import forms
from lineabase.models import Entrevistados, Encuestadores, OrganizacionApoyo
from lugar.models import (Pais, Departamento,
                                                 Municipio, Comunidad)
from .models import EncuestaRentabilidad
from configuracion.models import LineaTiempoCostos

from dal import autocomplete

class EntrevistadoForm(forms.ModelForm):
    class Meta:
        model = EncuestaRentabilidad
        fields = ('__all__')
        widgets = {
            'entrevistado': autocomplete.ModelSelect2(url='entrevistados-autocomplete')
        }

class EntrevistadosForm(forms.ModelForm):

    class Meta:
        model = Entrevistados
        fields = '__all__'
        widgets = {
                'departamento': autocomplete.ModelSelect2(url='depart-autocomplete',
                                                           forward=['pais']),
                 'municipio': autocomplete.ModelSelect2(url='municipio-autocomplete',
                                                           forward=['departamento']),
                 'comunidad': autocomplete.ModelSelect2(url='comunidad-autocomplete',
                                                           forward=['municipio']),
            }

def fecha_choice():
    years = []
    for en in EncuestaRentabilidad.objects.order_by('fecha').values_list('fecha', flat=True):
        years.append((en.year,en.year))
    return list(sorted(set(years)))

def ciclo_choice():
    ciclos = []
    for en in Ciclo.objects.all():
        ciclos.append((en.nombre,en.nombre))
    return list(sorted(set(ciclos)))

CHOICE_SEXO1 = (
    ('', '-------'),
    (1, 'Mujer'),
    (2, 'Hombre')
)

CHOICE_TAMANO_PARCELA1 = (
    ('', '-------'),
    (1, 'Pequeña (0.1 a 2 mz)'),
    (2, 'Mediana (2.1 a 5 mz)'),
    (3, 'Grande (Más de 5 mz)'),
)

CHOICE_RIEGO1 = (
    ('', '-------'),
    (1, 'No hay riego'),
    (2, 'Riego de baja intensidad'),
    (3, 'Riego de alta intensidad'),
)

CHOICE_TIPO_SISTEMA_AGROFORESTAL1 = (
    ('', '-------'),
    (1, 'SAF Cacao Sencillo'),
    (2, 'SAF Cacao Diversificado'),
    (3, 'SAF Cacao + Café Sencillo'),
    (4, 'SAF Cacao + Café Diversificado'),
)

CHOICE_VALORACION_SUELO1 = (
    ('', '-------'),
    (1, 'Óptimo'),
    (2, 'Medio óptimo'),
    (3, 'No óptimo'),
)

CHOICE_TIPO_MANEJO1 = (
    ('', '-------'),
    (1, 'Orgánico'),
    (2, 'Orgánico-químico'),
    (3, 'Químico'),
)

CHOICE_INTENSIDAD_MANEJO1 = (
    ('', '-------'),
    (1, 'No intensivo'),
    (2, 'Medio intensivo'),
    (3, 'Intensivo'),
)

class ConsultaFichaForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ConsultaFichaForm, self).__init__(*args, **kwargs)
        self.fields['fecha'].widget.attrs.update({'class': 'select2 form-control select2-multiple select2-hidden-accessible',
                                                                        'data-placeholder':'Escoge....', 'tabindex':'-1','area-hidden': 'true'})
        self.fields['pais'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['modelo'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['parcela'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['riego'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['saf'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['valoracion'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['manejo'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['intensidad'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['sexo'].widget.attrs.update({'class': 'select2 select2-container select2-container--default select2-container--above'})
        self.fields['productor'].widget.attrs.update({'class': 'form-control'})
    fecha = forms.MultipleChoiceField(choices=fecha_choice(), label="Años", required=True)
    pais = forms.ModelChoiceField(queryset=Pais.objects.all(), required=False)
    parcela = forms.ChoiceField(choices=CHOICE_TAMANO_PARCELA1,
                                                                    label="Tamaño de parcela", required=False)
    riego = forms.ChoiceField(choices=CHOICE_RIEGO1, required=False)
    saf = forms.ChoiceField(choices=CHOICE_TIPO_SISTEMA_AGROFORESTAL1,
                                                label="Tipo SAF", required=False)
    valoracion = forms.ChoiceField(choices=CHOICE_VALORACION_SUELO1,
                                                            label="Valoracion de suelo", required=False)
    manejo = forms.ChoiceField(choices=CHOICE_TIPO_MANEJO1, required=False)
    intensidad = forms.ChoiceField(choices=CHOICE_INTENSIDAD_MANEJO1, required=False)
    sexo = forms.ChoiceField(choices=CHOICE_SEXO1, required=False)
    productor = forms.CharField(max_length=250, required=False)
    modelo = forms.ModelChoiceField(queryset=LineaTiempoCostos.objects.all(), required=True)

templates/rentabilidad/consulta_form.html
<form class="form-horizontal" action="." method="POST">{% csrf_token %}
	<div class="form-group">
		<div class="row">
			<div class="col-4">
				<label for="fecha">Fecha</label>
				{{form.fecha}}
			</div>
			<div class="col-4">
				<label for="municipio">Pais</label>
				{{form.pais}}
			</div>
			<div class="col-4">
				<label for="organizacion">Modelo</label>
				{{form.modelo}}
			</div>
		</div> 
	</div>
	<div class="form-group">
		<div class="row">
			<div class="col-4">
				<label for="comunidad">Tipo de manejo</label>
				{{form.manejo}}
			</div>
			<div class="col-4">
				<label for="pais">Tamaño de la parcela</label>
				{{form.parcela}}
			</div>
			<div class="col-4">
				<label for="sexo">Intensidad de manejo</label>
				{{form.intensidad}}
			</div>
		</div> 
	</div>
	<div class="form-group">
		<div class="row">
			<div class="col-4">
				<label for="departamento">Riego</label>
				{{form.riego}}
			</div>
			<div class="col-4">
				<label for="productor">sexo</label>
				{{form.sexo}}
			</div>
			<div class="col-4">
				<label for="departamento">Tipo SAF</label>
				{{form.saf}}
			</div>
		</div> 
	</div>
	<div class="form-group">
		<div class="row">
			<div class="col-4">
				<label for="departamento">Valoración de suelo</label>
				{{form.valoracion}}
			</div>
			{% if request.user.is_authenticated %}
			<div class="col-4">
				<label for="productor">Productor</label>
				{{form.productor}}
			</div>
			{% endif %}
		</div> 
	</div>
	<div class="">
		<input type="submit" value="Consultar" id="boton" class="btn btn-success"/>
	</div>
</form>

templates/rentabilidad/consultarRentabilidad.html
{% extends "base.html" %}

{% load solo_tags %}

{% block content %}
{% get_solo 'configuracion.SiteConfiguration' as site_config %}
<div class="container-fluid" id="monitoreo_reta">
    <div class="row mt-30">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group float-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item">
                            <a href="/">Inicio</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{% url 'consulta-establecimiento' %}">Consultar Rentabilidad</a>
                        </li>
                    </ol>
                </div>
                <h4 class="page-title">CONSULTAR</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="mb-40">
                <div class="row">
                    <div class="col-lg-4 card-box shadow-c">

                        {%if centinela == 1 %}
                            <h4 class="header-title mb-0">Seleccione el Indicador: Rentabilidad</h4>
                            <hr>
                            {% include "rentabilidad/menu_rentabilidad.html" %}
                        {% else %}
                            <h4 class="header-title mb-0">Rentabilidad de sistemas agroforestales</h4>
                            <hr>
                             {% if  site_config.texto_rentabilidad %}
                            <p>{{site_config.texto_rentabilidad|safe}}</p>
                        {% else %}
                            <p>Aun sin texto</p>
                        {% endif %}
                        {%endif%}

                    </div>
                    <div class="col-lg-8 card-box">
                        <h4 class="header-title mb-4">Formulario de consulta: Rentabilidad</h4>
                        <div class="row">
                            <div class="col-md-12">
                                <form action="." method="POST">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="fecha">Fecha</label>
                                            {{form.fecha}}
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="municipio">Pais</label>
                                            {{form.pais}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                    <div class="col-sm-6">
                                            <label for="organizacion">Modelo</label>
                                            {{form.modelo}}
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="comunidad">Tipo de manejo</label>
                                            {{form.manejo}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="pais">Tamaño de la parcela</label>
                                            {{form.parcela}}
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="sexo">Intensidad de manejo</label>
                                            {{form.intensidad}}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="departamento">Riego</label>
                                            {{form.riego}}
                                        </div>
                                            <div class="col-sm-6">
                                                <label for="productor">sexo</label>
                                                {{form.sexo}}
                                            </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="departamento">Tipo SAF</label>
                                            {{form.saf}}
                                        </div>
                                        {% if request.user.is_authenticated %}
                                            <div class="col-sm-6">
                                                <label for="productor">Productor</label>
                                                {{form.productor}}
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="departamento">Valoración de suelo</label>
                                            {{form.valoracion}}
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <input type="submit" value="Consultar" id="boton" class="btn btn-success center-block"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<link href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function () {
    // Select2
    $(".select2").select2();
});

$("#id_productor").autocomplete({
    source: '{% url "productor-search"%}',
    minLength: 2,
  });

$('.botonera').slideDown('slow');

$("#id_pais").change(function () {
      var url = '/linea-base/ajax/load-departamentos/'
      var paisId = $("#id_pais").val();

    $.ajax({
        url: url,
        data: {
          'pais': paisId
        },
        success: function (data) {
          $("#id_departamento").html(data);
        }
    });
 });

$("#id_departamento").change(function () {
      var url = '/linea-base/ajax/load-municipios/'
      var departamentoId = $("#id_departamento").val();

    $.ajax({
        url: url,
        data: {
          'departamento': departamentoId
        },
        success: function (data) {
          $("#id_municipio").html(data);
        }
    });
 });

$("#id_municipio").change(function () {
      var url = '/linea-base/ajax/load-comunidad/'
      var municipioId = $("#id_municipio").val();

    $.ajax({
        url: url,
        data: {
          'municipio': municipioId
        },
        success: function (data) {
          $("#id_comunidad").html(data);
        }
    });
 });
</script>
{% endblock extra_js %}

templates/rentabilidad/filtros.html
<ol class="breadcrumb hide-phone p-0 m-0">
  <li class="breadcrumb-item">Filtros Seleccionados: </li>
    {%if num_familias%}
        <li class="breadcrumb-item"><b>Familias:</b>{{num_familias}}</li>
    {%endif%}
    {%if request.session.fecha%}
    <li class="breadcrumb-item"><b>Año:</b>{%for x in request.session.fecha%} {{x}}{% if forloop.last%}{%else%},{%endif%} {%endfor%}</li>
    {%endif%}
    {%if request.session.pais%}
    <li class="breadcrumb-item"><b>pais:</b> {{request.session.pais}}</li>
    {%endif%}
    {%if request.session.parcela%}
    <li class="breadcrumb-item"><b>Parcela:</b> {% if request.session.parcela == '1' %}Pequeña (0.1 a 2 mz){%elif request.session.parcela == '2'%}Mediana (2.1 a 5 mz){% else %}Grande (Más de 5 mz){%endif%}</li>
    {%endif%}
    {%if request.session.riego%}
    <li class="breadcrumb-item"><b>Riego:</b> {% if request.session.riego == '1' %}No hay riego{%elif request.session.riego == '2'%}Riego de baja intensidad{% else %}Riego de alta intensidad{%endif%}</li>
    {%endif%}
    {%if request.session.saf%}
    <li class="breadcrumb-item"><b>SAF:</b> {% if request.session.saf == '1' %}SAF Cacao Sencillo{%elif request.session.saf == '2'%}SAF Cacao Diversificado{%elif request.session.saf == '3'%}SAF Cacao + Café Sencillo{% else %}SAF Cacao + Café Diversificado{%endif%}</li>
    {%endif%}
    {%if request.session.valoracion%}
    <li class="breadcrumb-item"><b>Valoración:</b> {% if request.session.valoracion == '1' %}Óptimo{%elif request.session.valoracion == '2'%}Medio óptimo{% else %}No óptimo{%endif%}</li>
    {%endif%}
    {%if request.session.manejo%}
    <li class="breadcrumb-item"><b>Tipo manejo:</b> {% if request.session.manejo == '1' %}Orgánico{%elif request.session.manejo == '2'%}Orgánico-químico{% else %}Químico{%endif%}</li>
    {%endif%}
    {%if request.session.intensidad%}
    <li class="breadcrumb-item"><b>Intensidad:</b> {% if request.session.intensidad == '1' %}No intensivo{%elif request.session.intensidad == '2'%}Medio intensivo{% else %}Intensivo{%endif%}</li>
    {%endif%}
    {%if request.session.sexo%}
    <li class="breadcrumb-item"><b>Sexo:</b>{%if request.session.sexo == '1'%}Mujer{%else%}Hombre{%endif%}</li>
    {%endif%}
</ol>

templates/rentabilidad/ingresos_parcelas.html
{% extends "base.html" %}

{% load tools %}

{% block content %}
<div class="container-fluid" id="estado_finca">
    <div class="row mt-30">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="btn-group float-right">
                    <ol class="breadcrumb hide-phone p-0 m-0">
                        <li class="breadcrumb-item">
                            <a href="/">Inicio</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{% url 'consulta-rentabilidad' %}">Consultar</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">Rentabilidad</a>
                        </li>
                    </ol>
                </div>
                <h4 class="page-title">Ingresos de parcelas</h4>
            </div>
        </div>
    </div>
    <div class="row mb-50">
        <div class="col-md-2">
            {% include "rentabilidad/menu_salidas_rentabilidad.html" %}

        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <h4 class="header-title mb-4">Filtros Seleccionado</h4>
                        {% include "rentabilidad/filtros.html" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <h4 class="header-title">Ingreso bruto proyectado USD/ha por año</h4>
                        <ul class="list-inline mb-20">
                            <li class="list-inline-item"><strong>Número de parcelas: </strong> <kbd>{{numero_total_parcela}}</kbd></li>
                            <li class="list-inline-item"><strong>Areas de las parcelas (ha) total: </strong> <kbd>{{promedio_areas|floatformat:2}}</kbd></li>
                        </ul>
                        <div class="table-responsive">
                            <div id="modalidad1">
                                <table class="table table-bordered big-table">
                                    <thead class="bg-theme-colored-darker3">
                                        <tr>
                                            <th>Ingreso neto</th>
                                            <th>Frecuencia</th>
                                            <th>Promedio</th>
                                            <th>Mediana</th>
                                            <th>Minimo</th>
                                            <th>Maximo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for k,v  in ingresos.items %}
                                    <tr>
                                        <td>{{k}}</td>
                                            <td>{{v.0}}</td>
                                            <td>{{v.1|floatformat:2}}</td>
                                            <td>{{v.2|floatformat:2}}</td>
                                            <td>{{v.3|floatformat:2}}</td>
                                            <td>{{v.4|floatformat:2}}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
    $("#collapsefamilia").addClass('show');
    $(".item4").addClass('active');
    var flag = true;
    $(document).ready(function(){
        $('#mas').click(function(){
            if(flag==true){
                $('.botonera').slideDown('slow');
                $('#estado').html('<span><i class="fa fa-arrow-up"></i></span>');
                flag = false;
            }else if (flag==false){
                $('.botonera').slideUp('slow');
                $('#estado').html('<span><i class="fa fa-arrow-down"></i></span>');
                flag = true;
            }
            return false;
            });
        });
</script>
{% endblock extra_js %}

templates/rentabilidad/menu_rentabilidad.html
<div class="botonera">
        <a id="ancla" href="/rentabilidad/descripcion/" class="btn btn-primary waves-light waves-effect custom-btn">Descripcion de muestras</a>
        <a href="/rentabilidad/parcela/" class="btn btn-primary waves-light waves-effect custom-btn">Diseño de parcelas</a>
        <a href="/rentabilidad/costos/"class="btn btn-primary waves-light waves-effect custom-btn">Costo</a>
        <a href="/rentabilidad/ingresos/"class="btn btn-primary waves-light waves-effect custom-btn">Ingresos</a>
        <a href="/rentabilidad/modelado/"class="btn btn-primary waves-light waves-effect custom-btn"> Modelo de estimado de rentabilidad</a>
        <a href="/rentabilidad/rentabilidad/"class="btn btn-primary waves-light waves-effect custom-btn">Rentabilidad SAF</a>
</div>